# Generated by Django 4.0.6 on 2022-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('minimun', models.IntegerField(verbose_name='Minimun')),
                ('amount_per_package', models.IntegerField(verbose_name='Amount per package')),
                ('max_availability', models.IntegerField(verbose_name='Max availability')),
            ],
        ),
    ]
